### ISSUE TITLE
Bonus Rewards & More

### ISSUE THREAD

**Issue by Wazupbutrcup** [Maxlego08/zKoth#7]
Here's an updated version of the YAML file with explanations:
```yaml
type: CAPTURE
name: KOTH
capture: 30
cooldownStart: 300
stopAfterSeconds: 3600
startCommands: []
endCommands: []
enableStartCapMessage: true
enableLooseCapMessage: true
enableEverySecondsCapMessage: false
minLocation:
  world: playworld
  x: 445
  y: 93
  z: -223
maxLocation:
  world: playworld
  x: 451
  y: 86
  z: -217
scoreboard:
  cooldown:
    enable: false
    title: zKoth
    lines:
    - Default Configuration
  start:
    enable: false
    title: zKoth
    lines:
    - Default Configuration
hologram:
  enable: true
  lines: []
  world: playworld
  x: 448
  y: 90
  z: -220
progressBar:
  length: 10
  symbol: '-'
  completedColor: '&a'
  notCompletedColor: '&7'
loot:
  type: INVENTORY
  random: 100
  items:
    - H4sIAAAAAAAA/8WTwW4TMRCGJ00qki1SJcSRw9bnCO57JBQhQVGFRDlUVTXZnexa67W39ph2FeUZ+gYVHHgKLjwLT8I0rbJq4ArIB2vG4/m/GXsSgDHs6AL2G20p97jgrMWWfAJDxjKBJ8dxbnT+Mta15hM0kcIYntFVTsaQZbnBFLL1dl5T91xSjTx6ggk8PrR5hZYbiQsJAAzupJ72UtHOPWGtbbkDQ/PZwAASeFTo0BrsxjB6jw3B9VLRFXtU2elSzZ0pVMY+0lRpRkFT2QJNEDPagryR3MXGFdjrmrjyLpbVxuvmixhyIe4Dc2ecV5nCi4hqqlgExfoghaRvqVOrs41PrSYweuc8jaWiXdhb9gfw5XfS+/x/AbX02PWox9FLswOljaCl6/dI5T3CQ3T48f8ILzVXqVpNl9tSf+79i9xpGyrXblXwoOFf/2U5nXx5d9kT/rz5ln6UjiOnn9C36Ww9CwdbvEPYn8XArjlyBZlXyAiw930Ikze6oNcGy3A7GbJ2Zy5aHsAviykRBpMDAAA=
  bonusItems:
    - item: DIAMOND
      chance: 10
    - item: GOLD_INGOT
      chance: 20
    - item: IRON_INGOT
      chance: 30
```

Explanation:
I've changed the random value under loot to 100, ensuring that the guaranteed items are awarded 100% of the time.
Added a new field bonusItems under loot, containing a list of potential bonus items with their respective chances.
Each bonusItems entry includes an item (e.g., DIAMOND, GOLD_INGOT, IRON_INGOT) and its corresponding chance of being awarded as a bonus reward.
You can adjust the chance values according to the desired probability for each bonus item.
This configuration ensures that players receive the guaranteed item(s) every time, while also having a chance to receive bonus rewards based on the specified probabilities.
